services:
  - type: web
    plan: free
    name: juntavecinal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn juntavecinal.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
    databases:
      - name: mysitedb
        databaseName: digitalizacion_junta_vecinal
        user: digitalizacion_junta_vecinal_user