services:
  - type: web
    plan: free
    name: juntavecinal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn juntavecinal.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false