services:
  - type: web
    plan: free
    name: juntavecinal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn juntavecinal.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        fromDatabase:
          name: digitalizacion_junta_vecinal
          property: database
      - key: DB_USER
        fromDatabase:
          name: digitalizacion_junta_vecinal
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: digitalizacion_junta_vecinal
          property: password
      - key: DB_HOST
        fromDatabase:
          name: digitalizacion_junta_vecinal
          property: host
      - key: DB_PORT
        value: 5432
      - key: SECRET_KEY
        generateValue: true
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false