# Generated by Django 5.1.1 on 2024-10-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='date_vigencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
