# Generated by Django 5.1.1 on 2024-10-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_date_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
