# Generated by Django 5.1.1 on 2024-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
