# Generated by Django 5.1.1 on 2024-11-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='validity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
