# Generated by Django 5.1.1 on 2024-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_certificaterequest_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='reason_of_request',
            field=models.IntegerField(choices=[(1, 'Legales'), (2, 'Educativos'), (3, 'Laborales'), (4, 'Bancarios'), (5, 'Médicos'), (6, 'que se estimen convenientes')], default=6),
        ),
    ]
