# Generated by Django 5.1.1 on 2024-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_certificaterequest_reason_of_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='type_of_certificate',
            field=models.IntegerField(choices=[(1, 'Certificado de residencia')], default=1),
        ),
    ]
