# Generated by Django 5.1.1 on 2024-10-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
