# Generated by Django 5.1.1 on 2024-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_housing_latitude_housing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='rut',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
