# Generated by Django 5.1.1 on 2024-11-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_familymember_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='comuna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
